// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormAddImagesController from "./form_add_images_controller"
application.register("form-add-images", FormAddImagesController)

import FormAddProductController from "./form_add_product_controller"
application.register("form-add-product", FormAddProductController)

import FormRemoveImagesController from "./form_remove_images_controller"
application.register("form-remove-images", FormRemoveImagesController)

import FormRemoveProductController from "./form_remove_product_controller"
application.register("form-remove-product", FormRemoveProductController)

import FormResetController from "./form_reset_controller"
application.register("form-reset", FormResetController)
